### ISSUE TITLE
Senior Design Roadmap

### ISSUE THREAD

**Issue by moneimne** [moneimne/WebGL-PBR#1]
- [x] Reference App for glTF PBR extension
  - [x] Load glTF assets
  - [x] Finish PBR shader
  - [x] Add image-based lighting
- [ ] Add a stage to glTF Pipeline that parses the PBR extension and generates the shaders required to render it
- [ ] Finish PBR tutorial
  - [ ] Finalize theory
  - [ ] Add images from reference app

**Comment by mlimper** [comment]
Great to see this!

Here's a PR to generate tangents / binormals with glTF-pipeline:
https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/203

This was the simple Hammer asset I generated at some point partially by hand and partially using glTF-pipeline:
https://github.com/tsturm/glTF/tree/master/extensions/Vendor/FRAUNHOFER_materials_pbr/example/simple-pbr/assets/hammer

**Comment by moneimne** [comment]
Thanks for the resources, @mlimper!

**Comment by pjcozzi** [comment]
> This was the simple Hammer asset I generated at some point partially by hand and partially using glTF-pipeline:
https://github.com/tsturm/glTF/tree/master/extensions/Vendor/FRAUNHOFER_materials_pbr/example/simple-pbr/assets/hammer

@mlimper just a reminder that contributions to the [glTF Samples repo](https://github.com/KhronosGroup/glTF-Sample-Models) are always welcome!  We'll especially need some great PBR models.

**Comment by pjcozzi** [comment]
Work-in-progress glTF PBR demo: http://www.seas.upenn.edu/~moneimne/WebGL-PBR/

**Comment by mlimper** [comment]
Wow, nice! Happy to see this progress!

**Comment by javagl** [comment]
There are some glitches in FF...

    Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/  jquery-3.1.1.js:9425:4
    Syntax-Fehler  pbr-vert.glsl:1:1
    Syntax-Fehler  pbr-frag.glsl:1:1
    nicht wohlgeformt  Helmet.gltf:1:1
    Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  scene.js:218:5
    Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401  scene.js:218:5

and in Chrome...

    [.Offscreen-For-WebGL-040E9338]RENDER WARNING: there is no texture bound to the unit 0

so that the controls don't seem to work (for me).

But the helmet is rendered nevertheless, and looks *awesome*. 

What is the intended license of all this? (I considered to try this in my glTF viewer, and wondered under which conditions I can use the shaders...)

**Comment by moneimne** [comment]
Thanks for letting me know about the errors in Firefox, @javagl! 

This project is still very much a work in progress, so many things are subject to change. I have been primarily testing in Chrome, so I am aware of the error there, but I will have to look into the FF issues.

The shaders also don't compute lighting correctly yet, so I wouldn't use them yet, but I just added an MIT license to the repository.

**Comment by javagl** [comment]
Just for the case that someone is interested: I created a copy of the helmet asset that (as far as reasonably possible) passes validation, and can be used with "any" glTF viewer (that is: it does not use the extensions, but the shaders from this repository). I intend to use it for tests while implementing the PBR functionality for glTF 2.0, an uploaded it to https://github.com/javagl/gltfTestModels/tree/master/DamagedHelmetModified

**Comment by pjcozzi** [comment]
Assuming it is inline with the model's terms of use, it would be great to have it in https://github.com/KhronosGroup/glTF-Sample-Models when ready.

**Comment by javagl** [comment]
The license is Creative Commons Attribution-NonCommercial, so this should be fine, but right now, it's still rather "experimental", first, regarding the shaders, but also considering the changes that are to be expected for the transition to glTF 2.0.

**Comment by moneimne** [comment]
**Weekly Goal (1/23 - 1/30)**

- Add environment maps
- Update shader to include IBL computations

**Comment by emackey** [comment]
@moneimne OK to close this?

**Comment by moneimne** [comment]
> OK to close this?

Yes! Thanks for checking.
